                  
CREATE TABLE Ingestion.Retailer(
	RETAILER_NAME VARCHAR(50),
	RETAILER_SITE_CODE DECIMAL(10,0),
	RETAILER_CONTACT_CODE DECIMAL(10,0),
	SOURCE_ID VARCHAR(255),
	DataDate DATE,
	UpdateDate DATE
)--1
CREATE TABLE Ingestion.WAREHOUSE(
	BRANCH_CODE DECIMAL(10,0) PRIMARY KEY,
	[ADDRESS] NVARCHAR(50),
	CITY NVARCHAR(40),
	POSTAL_ZONE NVARCHAR(10),
	COUNTRY_CODE DECIMAL(10,0),
	WAREHOUSE_BRANCH_CODE DECIMAL(10,0),
	SOURCE_ID VARCHAR(255),
	DataDate DATE,
	UpdateDate DATE
)--2
CREATE TABLE Ingestion.COUNTRY(
	COUNTRY_CODE DECIMAL(22,10) PRIMARY KEY,
	COUNTRY_ID NVARCHAR(3),
	COUNTRY_NAME NVARCHAR(50),
	SOURCE_ID VARCHAR(255),
	DataDate DATE,
	UpdateDate DATE
)--3
CREATE TABLE Ingestion.RETURN_REASON(
	RETURN_REASON_CODE DECIMAL(10,0) PRIMARY KEY,
	RETURN_REASON_DESC NVARCHAR(50),
	SOURCE_ID VARCHAR(255),
	DataDate DATE,
	UpdateDate DATE
)--4
CREATE TABLE Ingestion.ORDER_METHOD(
	METHOD_CODE DECIMAL(10,0),
	METHOD_NAME VARCHAR(50),
	SOURCE_ID VARCHAR(255),
	DataDate DATE,
	UpdateDate DATE
)--5
CREATE TABLE Ingestion.PRODUCT(
	PRODUCT_NUMBER DECIMAL(10,0) primary key,
	BASE_PRODUCT_NUMBER DECIMAL(10,0),
	INTRODUCTION_DATE DATE not null,
	DISCONTINUED_DATE DATE null,
	PRODUCT_TYPE_CODE DECIMAL(10,0),
	PRODUCT_COLOR_CODE DECIMAL(10,0),
	PRODUCT_SIZE_CODE DECIMAL(10,0),
	PRODUCT_BRAND_CODE DECIMAL(10,0),
	PRODUCTION_COST DECIMAL(19,2),
	GROSS_MARGIN FLOAT,
	PRODUCT_IMAGE VARCHAR(50),
	SOURCE_ID VARCHAR(255),
	DataDate DATE,
	UpdateDate DATE
)--6
CREATE TABLE Ingestion.ORDER_HEADER(
	ORDER_NUMBER DECIMAL(10,0) primary key,
	RETAILER_NAME NVARCHAR(50) not null,
	RETAILER_NAME_MB NVARCHAR(50),
	RETAILER_SITE_CODE DECIMAL(10,0),
	RETAILER_CONTACT_CODE DECIMAL(10,0),
	RAW_STAFF_CODE DECIMAL(10,0),
	RAW_BRANCH_CODE DECIMAL(10,0),
	ORDER_DATE DATE not null,
	ORDER_CLOSE_DATE DATE,
	ORDER_METHOD_CODE DECIMAL(10,0),
	SOURCE_ID VARCHAR(255),
	DataDate DATE,
	UpdateDate DATE
)--7
CREATE TABLE Ingestion.BRANCH(
	BRANCH_CODE DECIMAL(22,10) PRIMARY KEY,
	ADDRESS1 nvarchar(100),
	ADDRESS1_MB nvarchar(100),
	ADDRESS2 nvarchar(100),
	ADDRESS2_MB nvarchar(100),
	CITY nvarchar(80),
	CITY_MB nvarchar(80),
	PROV_STATE nvarchar(100),
	PROV_STATE_MB nvarchar(100),
	POSTAL_ZONE nvarchar(20),
	COUNTRY_CODE DECIMAL(22,10),
	ORGANIZATION_CODE nvarchar(40),
	WAREHOUSE_BRANCH_CODE float,
	SOURCE_ID VARCHAR(255),
	DataDate DATE,
	UpdateDate DATE
)--8
CREATE TABLE Ingestion.PRODUCT_NAME_LOOKUP(
	PRODUCT_NUMBER DECIMAL(10,0),
	PRODUCT_LANGUAGE VARCHAR(4),
	PRODUCT_NAME NVARCHAR(50),
	PRODUCT_DESCRIPTION NVARCHAR(255),
	SOURCE_ID VARCHAR(255),
	DataDate DATE,
	UpdateDate DATE
)--9
CREATE TABLE Ingestion.INVENTORY_LEVELS(
	INVENTORY_YEAR DECIMAL(5,0) not null,
	INVENTORY_MONTH DECIMAL(5,0),
	WAREHOUSE_BRANCH_CODE DECIMAL(10,0),
	PRODUCT_NUMBER DECIMAL(10,0),
	OPENING_INVENTORY DECIMAL(10,0),
	QUANTITY_SHIPPED DECIMAL(10,0),
	ADDITIONS DECIMAL(10,0),
	UNIT_COST DECIMAL(19,2),
	CLOSING_INVENTORY DECIMAL(10,0),
	AVERAGE_UNIT_COST DECIMAL(19,2),
	SOURCE_ID VARCHAR(255),
	DataDate DATE,
	UpdateDate DATE
)--10
CREATE TABLE Ingestion.ORDER_DETAILS(
	ORDER_DETAIL_CODE DECIMAL(10,0) PRIMARY KEY,
	ORDER_NUMBER DECIMAL(10,0),
	SHIP_DATE DATE,
	PRODUCT_NUMBER DECIMAL(10,0),
	PROMOTION_CODE DECIMAL(10,0),
	QUANTITY DECIMAL(10,0) not null check (QUANTITY > 0),
	UNIT_COST DECIMAL(19,2) not null check (UNIT_COST > 0),
	UNIT_PRICE DECIMAL(19,2) not null check (UNIT_PRICE > 0),
	UNIT_SALE_PRICE DECIMAL(19,2) not null check (UNIT_SALE_PRICE > 0),
	SOURCE_ID VARCHAR(255),
	DataDate DATE,
	UpdateDate DATE
)--11
CREATE TABLE Ingestion.RETURNED_ITEM(
	RETURN_CODE DECIMAL(10,0) PRIMARY KEY,
	RETURN_DATE DATE,
	ORDER_DETAIL_CODE DECIMAL(10,0),
	RETURN_REASON_CODE DECIMAL(10,0),
	RETURN_QUANTITY DECIMAL(10,0),
	ASSIGNED_TO DECIMAL(10,0),
	FOLLOW_UP_CODE DECIMAL(10,0),
	COMMENTS VARCHAR(255),
	DATE_ADVISED DATE,
	SOURCE_ID VARCHAR(255),
	DataDate DATE,
	UpdateDate DATE
)--12